name = "wordbook-counter"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
API_SECRET = "danci-wordbook-counter-public-secret-2026"

[[kv_namespaces]]
binding = "DOWNLOAD_COUNTS"
id = "46526139f7934fa486925512a123dae3"
